image: python:3-slim
stages:
  - ansible-lint
  - ansible-syntax
  - deploy

before_script:
  - pip install --upgrade ansible ansible-lint
  - ansible --version
  - ansible-lint --version

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint *.yml

ansible-syntax:
  stage: ansible-syntax
  script:
    - ansible-playbook --inventory hosts --syntax-check *.yml

deploy:
  stage: deploy
  image: python:latest
  only:
    - /^version.*$/
  services:
    - docker:dind
  before_script:
    - echo "$SSH_PRIVATE_KEY_RND_CICD" > ssh_key
    - chmod 400 ssh_key
    - eval $(ssh-agent -s)
    - ssh-add ssh_key
    - rm ssh_key
  script:
    - apt-get update && apt-get install -y ansible
    - pip3 install docker
    - ansible-playbook -i hosts rnd-cicd-runner.yml -u root  -e "gitlab_runner_automation_token=$GITLAB_RUNNER_AUTOMATION_TOKEN gitlab_runner_rnd_infra_token=$GITLAB_RUNNER_RND_INFRA_TOKEN gitlab_runner_rnd_token=$GITLAB_RUNNER_RND_TOKEN gitlab_runner_train_token=$GITLAB_RUNNER_TRAIN_TOKEN"
    - ansible-playbook -i hosts grafana-promtail.yml -u root
  when: manual