- name: Create GitLab Runner volume
  community.docker.docker_volume:
    name: AUTOMATION-group-gitlab-runner-config

- name: Start GitLab Runner
  community.docker.docker_container:
    name: "{{ gitlab_runner_description }}"
    image: "{{ gitlab_runner_image }}"
    networks:
      - name: fltechnics
    state: started
    published_ports:
      - "9258:9252"
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - AUTOMATION-group-gitlab-runner-config:/etc/gitlab-runner

- name: Check if runner config exists
  ansible.builtin.command: docker run --rm -v AUTOMATION-group-gitlab-runner-config:/etc/gitlab-runner gitlab/gitlab-runner list
  register: configured_runners
  changed_when: false

- name: Set fact if registration is needed
  ansible.builtin.set_fact:
    runner_registration_needed: "{{ gitlab_runner_description not in configured_runners.stderr }}"
  changed_when: false

- name: Register GitLab Runner
  community.docker.docker_container:
    name: "{{ gitlab_runner_description }}"
    image: "{{ gitlab_runner_image }}"
    auto_remove: true
    networks:
      - name: fltechnics
    published_ports:
      - "9258:9252"
    volumes:
      - AUTOMATION-group-gitlab-runner-config:/etc/gitlab-runner
    command: >
      register --non-interactive
      --executor "docker"
      --docker-image "docker:dind"
      --docker-volumes "/var/run/docker.sock:/var/run/docker.sock"
      --url "https://gitlab.fltechnics.com"
      --registration-token "{{ gitlab_runner_automation_token }}"
      --description "{{ gitlab_runner_description }}"
      --run-untagged="true"
      --locked="false"
      --access-level="not_protected"
  when: runner_registration_needed

- name: Start GitLab Runner after registration
  community.docker.docker_container:
    name: "{{ gitlab_runner_description }}"
    image: "{{ gitlab_runner_image }}"
    networks:
      - name: fltechnics
    state: started
    published_ports:
      - "9258:9252"
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - AUTOMATION-group-gitlab-runner-config:/etc/gitlab-runner
  when: runner_registration_needed
