positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.231.235:3100/loki/api/v1/push

scrape_configs:
  - job_name: runner_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values:
              - "logging=runnner_logs"
    relabel_configs:
      - source_labels: ['__timestamp__']
        action: drop
        regex: '.+'
        modulus: 576000
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
